server:
  port: 8111
spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto:
        create
  datasource:
    url:
      postgres://avnadmin:AVNS_5vlCXknONwO5yCp_LdF@pg-1ac0a42c-hamzaelgarai10-fb28.a.aivencloud.com:22213/defaultdb?sslmode=require
    username:
      avnadmin
    password:
      AVNS_5vlCXknONwO5yCp_LdF




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
