server:
  port: 8112
spring:
  application:
    name: courses-ms
  jpa:
    hibernate:
      ddl-auto:
        create
    database: postgresql
  datasource:
    url:
      jdbc:postgresql://pg-1ac0a42c-hamzaelgarai10-fb28.a.aivencloud.com:22213/defaultdb
    username:
      avnadmin
    password:
      AVNS_5vlCXknONwO5yCp_LdF
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
