server:
  port: 8111
spring:
  application:
    name: student-ms
  jpa:
    hibernate:
      ddl-auto:
        create
  datasource:
    url:
      jdbc:mysql://localhost:3306/student_ms
    username:
      root
    password:
      Massaq51354




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true